# The Numpy array object

# NumPy Arrays

**python objects:** 

1. high-level number objects: integers, floating point
2. containers: lists (costless insertion and append), dictionaries (fast lookup)

**Numpy provides:**

1. extension package to Python for multi-dimensional arrays
2. closer to hardware (efficiency)
3. designed for scientific computation (convenience)
4. Also known as array oriented computing

In [2]:
import numpy as np

a = np.array([0, 1, 2, 3])

print(a)

print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


**Numpy Arrays - Why it is useful:** Memory-efficient container that provides fast numerical operations.

In [3]:
# python lists
L = range(1000)

%timeit [i**2 for i in L]

102 μs ± 5.39 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [4]:
# numpy arrays
a = np.arange(1000)

%timeit a**2

2.95 μs ± 236 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# 1. Creating arrays

**1.1.  Manual Construction of arrays**

In [31]:
# 1-D numpy arrays
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [32]:
a.ndim

1

In [33]:
a.shape

(5,)

In [34]:
len(a)

5

In [35]:
# 2-D numpy arrays
b = np.array([[2, 3, 4], [8, 6, 0]])
print(b)

[[2 3 4]
 [8 6 0]]


In [37]:
b.ndim

2

In [38]:
b.shape

(2, 3)

In [39]:
len(b)

2

In [40]:
# 3-D numpy arrays
c = np.array([[[1, 2], [3, 4], [6, 7]]])
c

array([[[1, 2],
        [3, 4],
        [6, 7]]])

In [41]:
c.ndim

3

In [42]:
c.shape

(1, 3, 2)

In [43]:
len(c)

1

**1.2  Functions for creating arrays**

**np.arange**

In [50]:
# using arange function

# arange is an array-valued version of the built-in Python range function

a = np.arange(10) # 0, 1, 2 ... n-1
print(a)

b = np.arange(0, 10, 3) # np.arange(start, end, step)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 3 6 9]


**np.linspace**

In [51]:
# using linspace (linear space) function

c = np.linspace(0, 1, 6) # np.linspace(start, stop, step)
c

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

**np.ones**

In [53]:
d = np.ones((3, 3))
print(d)

e = np.ones((3, 2))
print(e)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


**np.zeros**

In [54]:
f = np.zeros((3, 2))
print(f)

g = np.zeros((2, 2))
print(g)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]]


**np.eye**

In [56]:
i = np.eye(3)
print(i)

i2 = np.eye(3, 2)
print(i2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0.]
 [0. 1.]
 [0. 0.]]


**np.diag**

In [58]:
d = np.diag(range(1, 5))
print(d)

d2 = np.diag(d) # extracting the diagonal elements from numpy array 'd'
print(d2)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[1 2 3 4]


**np.random.rand**

In [61]:
#create array using random

#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

r = np.random.rand(4) 
r

array([0.20044803, 0.60588444, 0.75736237, 0.06331828])

**np.random.randn**

In [63]:
r2 = np.random.randn(4) #Return a sample (or samples) from the “standard normal” distribution or Gausian distribution
r2

array([-0.55452387,  1.87246463, -1.02279582, -0.44113014])

**np.random.randint**

In [66]:
a

array([ 3,  1,  3, 16,  5,  7, 10,  9,  1,  7, 16, 17, 18, 10, 10],
      dtype=int32)

# 2. Basic DataTypes

You may have noticed that, in some instances, array elements are displayed with a **trailing dot (e.g. 2. vs 2)**. This is due to a difference in the **data-type** used:

In [73]:
a = np.arange(15)
a.dtype

dtype('int64')

In [74]:
# You can explicitly specify which data-type you want

b = np.arange(15, dtype='float64')
b

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

#The default data type is float for zeros, ones, eye functions
z = np.zeros((3,3))
print(z, z.dtype)

o = np.ones((3,2))
print(o, o.dtype)

e = np.eye(2,3)
print(e, e.dtype)

**other datatypes**

In [77]:
c = np.array([1+4j, 2-3j])
print(c, c.dtype)

[1.+4.j 2.-3.j] complex128


In [78]:
b = np.array([True, False, False, True])
b, b.dtype

(array([ True, False, False,  True]), dtype('bool'))

In [79]:
s = np.array(['Sarath', 'Babu', 'Akash'])
s, s.dtype

(array(['Sarath', 'Babu', 'Akash'], dtype='<U6'), dtype('<U6'))

**Each built-in data type has a character code that uniquely identifies it.**

'b' − boolean

'i' − (signed) integer

'u' − unsigned integer

'f' − floating-point

'c' − complex-floating point

'm' − timedelta

'M' − datetime

'O' − (Python) objects

'S', 'a' − (byte-)string

'U' − Unicode

'V' − raw data (void)

**For more details**

**https://docs.scipy.org/doc/numpy-1.10.1/user/basics.types.html**

In [80]:
a = np.array([1, 'h', 3.])
a, a.dtype

(array(['1', 'h', '3.0'], dtype='<U32'), dtype('<U32'))

In [81]:
a = np.array([1, 3, 4.])
a, a.dtype

(array([1., 3., 4.]), dtype('float64'))

In [82]:
d = np.array([1, 5, 3])
d, d.dtype

(array([1, 5, 3]), dtype('int64'))

# 3. Indexing & Slicing

**3.1 Indexing**

The items of an array can be accessed and assigned to the same way as other **Python sequences (e.g. lists)**:

In [84]:
a = np.arange(10)

print(a[5])  #indices begin at 0, like other Python sequences (and C/C++)

5


In [91]:
# For multidimensional arrays, indexes are tuples or lists of integers

a = np.diag([1, 2, 3])

print(a)

print(a[1, 1])

print(a[1]) # returning row with index 1 in the numpy array

[[1 0 0]
 [0 2 0]
 [0 0 3]]
2
[0 2 0]


In [92]:
a[(2, 1)] = 5 # assigning value

a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [93]:
a[[0,1]] = 50 # assigning value

a

array([[50, 50, 50],
       [50, 50, 50],
       [ 0,  5,  3]])

In [94]:
a[(0,1)] = 115 # assigning value

a

array([[ 50, 115,  50],
       [ 50,  50,  50],
       [  0,   5,   3]])

**3.2 Slicing**

In [95]:
a = np.arange(10)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
a[1:7:2] # slicing - array_name[start_index:end_index(exclusive):step_size]

array([1, 3, 5])

In [97]:
# we can also combine assignment and slicing

a[5:] = 10

a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [102]:
b = np.arange(21, 26)

In [103]:
a[5:] = b[::-1] # reverse assignment of numpy array 'b' to numpy array 'a'

a

array([ 0,  1,  2,  3,  4, 25, 24, 23, 22, 21])

# 4. Copies and Views

A slicing operation creates a view on the original array, which is just a way of accessing array data. Thus the original array is not copied in memory. You can use **np.shares_memory()** to check if two arrays share the same memory block. 

**When modifying the view, the original array is modified as well:**

In [105]:
a = np.arange(10)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**shallow copy**

In [106]:
b = a[::2]

b

array([0, 2, 4, 6, 8])

In [109]:
np.shares_memory(a, b)

True

In [108]:
id(a[0]), id(b[0])

(2286426457872, 2286426457872)

In [110]:
id(a[4]), id(b[4])

(2286426456432, 2286426456432)

In [112]:
b[0] = 10

print(b)

[10  2  4  6  8]


In [113]:
a # eventhough we modified b,  it updated 'a' because both shares same memory

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

**deep copy**

In [114]:
a = np.arange(10)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
c = a[::2].copy() # force a copy

c

array([0, 2, 4, 6, 8])

In [116]:
np.shares_memory(a, c)

False

In [118]:
id(a[0]), id(c[0]) # below no. thousand every number is only created once and referenced but changes in one will not get reflected in another

(2286426460080, 2286426460080)

In [119]:
c[0] = 90

In [120]:
c

array([90,  2,  4,  6,  8])

In [121]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
a = 10
b = 10

In [124]:
id(a), id(b)

(140734991873224, 140734991873224)

In [125]:
a = 1000
b = 1000

In [126]:
id(a), id(b)

(2286426459888, 2286426459952)

# 5. Fancy Indexing

NumPy arrays can be indexed with slices, but also with boolean or integer arrays **(masks)**. This method is called **fancy indexing**. **It creates copies not views**.

**Using Boolean Mask**

In [127]:
a = np.random.randint(1, 20, 15)

a

array([13, 11, 17,  4, 18,  8, 18,  6,  9, 12, 11, 18,  5,  5,  5],
      dtype=int32)

In [129]:
mask = (a % 2 == 0)
mask

array([False, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True, False, False, False])

In [138]:
lst = [] # emtpy list

for x in mask:
    if x:
        lst.append(1)
    else:
        lst.append(0)

print(lst)

mask01 = np.array(lst)
mask01

[0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0]


array([0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0])

In [139]:
result1 = a[mask] # mask with boolean values (True or False) returns the values in that numpy array where they are True only
result1

array([ 4, 18,  8, 18,  6, 12, 18], dtype=int32)

In [140]:
result2 = a[mask01] # mask with 0 or 1 returns the values in numpy array with index 0 or 1
result2

array([13, 13, 13, 11, 11, 11, 11, 11, 13, 11, 13, 11, 13, 13, 13],
      dtype=int32)

In [141]:
extract_from_a = a[mask]

extract_from_a

array([ 4, 18,  8, 18,  6, 12, 18], dtype=int32)

**Indexing with a mask can be very useful to assign a new value to a sub-array:**

In [142]:
a[mask] = -1 # mask is marked True where elements in numpy array are even number so they will be assigned -1

a

array([13, 11, 17, -1, -1, -1, -1, -1,  9, -1, 11, -1,  5,  5,  5],
      dtype=int32)

**Indexing with an array of integers**

In [143]:
a = np.arange(1, 30)

a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [146]:
#Indexing can be done with an array of integers

a[[2, 7, 8, 3, 2, 20, 28, 2, 3, 8, 12, 15, 11, 12]]

array([ 3,  8,  9,  4,  3, 21, 29,  3,  4,  9, 13, 16, 12, 13])

In [148]:
# New values can be assigned to those array of indices

a[[9, 12, 15, 17]] = -122

a

array([   1,    2,    3,    4,    5,    6,    7,    8,    9, -122,   11,
         12, -122,   14,   15, -122,   17, -122,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29])