In [2]:
import numpy as np

# Elementwise Operations

Mostly all operations in numpy arrays are elementwise operations

**1. Basic Operations**

**with scalars**

In [10]:
a = np.array([1, 2, 3, 4])

a

array([1, 2, 3, 4])

In [11]:
a + 1

array([2, 3, 4, 5])

In [12]:
a ** 2

array([ 1,  4,  9, 16])

**All Arithmetic operator operates elementwise**

In [13]:
b = np.ones(4) + 1

b

array([2., 2., 2., 2.])

In [14]:
a - b

array([-1.,  0.,  1.,  2.])

In [15]:
a * b # elementwise multiplication not matrix multiplication

array([2., 4., 6., 8.])

In [18]:
a.dot(b)

np.float64(20.0)

In [19]:
c = np.diag(a)

c

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [20]:
a.dot(c)

array([ 1,  4,  9, 16])

**comparisions(Relational Operators):** <, >, <=, >=, ==, !=

In [23]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])

In [24]:
a == b

array([False,  True, False,  True])

In [25]:
a != b

array([ True, False,  True, False])

In [26]:
a < b

array([ True, False, False, False])

In [27]:
a > b

array([False, False,  True, False])

In [28]:
a <= b

array([ True,  True, False,  True])

In [29]:
a >= b

array([False,  True,  True,  True])

**np.array_equal**

In [30]:
# array-wise comparisions
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [31]:
np.array_equal(a, b) # returns "True" if all elements of 'a' are equal with all elements of 'b' otherwise "False"

False

In [32]:
np.array_equal(a, c)

True

**Logical Operations** -> logical_and, logical_or, logical_not, logical_xor

In [43]:
a = np.array([1, 0, 0, 1, 0], dtype=bool)
b = np.array([0, 2, 2, 1, 0])

print(a, b)

[ True False False  True False] [0 2 2 1 0]


In [44]:
np.logical_and(a, b)

array([False, False, False,  True, False])

In [45]:
np.logical_or(a, b)

array([ True,  True,  True,  True, False])

In [46]:
np.logical_not(a)

array([False,  True,  True, False,  True])

In [47]:
np.logical_xor(a, b)

array([ True,  True,  True, False, False])

**Transcendental functions** -> sin, cos, tan, sec, cosec, cot, log, exp

In [55]:
a = np.arange(5)

a

array([0, 1, 2, 3, 4])

In [56]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [57]:
np.log(a)

C:\Users\Sridharan\AppData\Local\Temp\ipykernel_31936\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [58]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

**Shape Mismatch**

In [59]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [60]:
a + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

# Basic Reductions

**computing sums**

In [62]:
a = np.arange(10)

print(a)

print(np.sum(a))
print(a.sum())

[0 1 2 3 4 5 6 7 8 9]
45
45


In [3]:
# sum by rows and columns for 2-D arrays and we can do this for n-D arrays also
x = np.array([[1, 1], [2, 2]])

print(x)

x.sum()

[[1 1]
 [2 2]]


np.int64(6)

In [65]:
x.sum(axis=0) # axis = 0 -> first dimension (column-wise)

array([3, 3])

In [66]:
x.sum(axis=1) # axis = 1 -> second dimension (row-wise)

array([2, 4])

In [67]:
x.sum(axis=1).T # just doing transpose operation

array([2, 4])

In [68]:
x.sum(axis=-1) # axis = -1 -> second dimension (row-wise) -> axis array for numpy array x with values = [0 (column), 1 (row)]

array([2, 4])

In [69]:
x.sum(axis=-2) # axis = -2 -> first dimension (column-wise)

array([3, 3])

In [70]:
x.sum(axis=-3)

AxisError: axis -3 is out of bounds for array of dimension 2

**other reductions**

In [71]:
x = np.array([1, 5, 2])

x

array([1, 5, 2])

In [72]:
x.min()

np.int64(1)

In [73]:
np.max(x)

np.int64(5)

In [74]:
np.argmin(x) # argmin - gives the index of the minimum element

np.int64(0)

In [75]:
x.argmax() # argmax - gives the index of the maximum element

np.int64(1)

In [8]:
# for 2-D arrays
x = np.array([[1, 1], [2, 2]])

x

array([0, 0])

In [7]:
x.min()

np.int64(1)

In [80]:
np.max(x)

np.int64(2)

In [78]:
np.argmin(x)

np.int64(0)

In [79]:
x.argmax()

np.int64(2)

In [81]:
# min and max for column-wise and row-wise
x.min(axis=0) # first dimension (column-wise)

array([1, 1])

In [82]:
x.max(axis=0) # first dimension (column-wise)

array([2, 2])

In [83]:
x.min(axis=1) # second dimension (row-wise)

array([1, 2])

In [84]:
x.max(axis=-1) # last dimension (row-wise)

array([1, 2])

In [85]:
x.argmax(axis=-1) # last dimension (row-wise)

array([0, 0])

In [9]:
x.argmax(axis=1)

array([0, 0])

**logical operations**

In [4]:
np.all([True, False, True]) # all is same as logical_and

np.False_

In [5]:
np.any([True, False, False]) # any is same as logical_or

np.True_

In [8]:
# Note: can be used for array comparisions

a = np.zeros((50, 50)) # zero matrix - with 50 x 50 size

print(a)

np.any(a != 0)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


np.False_

In [9]:
np.all(a == a)

np.True_

In [10]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

((a >= b) & (b <= c)).all()

np.False_

In [11]:
((a <= b) & (b <= c)).all()

np.True_

**Statistics**

In [12]:
x = np.array([1, 3, 2, 1])
y = np.array([[1, 5, 4], [3, 11, 7]])

In [13]:
x.mean()

np.float64(1.75)

In [15]:
x.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [16]:
np.median(x)

np.float64(1.5)

In [17]:
x.std()

np.float64(0.82915619758885)

In [18]:
# for 2-D array 'y'- for row-wise and column-wise statistics
y

array([[ 1,  5,  4],
       [ 3, 11,  7]])

In [19]:
y.mean(axis=0) # first dimension / first axis - column-wise - mean

array([2. , 8. , 5.5])

In [20]:
y.mean(axis=1) # second dimension / second axis - row-wise - mean

array([3.33333333, 7.        ])

In [21]:
y.mean(axis=-1) # last dimension / last axis - row-wise - mean -> axis array - [0, 1] -> where 0-column, 1-row

array([3.33333333, 7.        ])

In [22]:
y.mean(axis=-2) # second last dimension / second last axis - column-wise - mean

array([2. , 8. , 5.5])

In [23]:
np.median(y, axis=1) # second dimension / second axis - row-wise - median

array([4., 7.])

In [24]:
np.std(y, axis=0) # first dimension / first axis - column-wise - std

array([1. , 3. , 1.5])

**Example:**

Data in populations.txt describes the populations of hares(rabbits), lynxes(type of wild cats) and carrots in northern Canada during 20 years.

In [25]:
# load txt data into numpy array object
data = np.loadtxt('populations.txt')

In [26]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [27]:
year, hares, lynxes, carrots = data.T # columns to variables

In [28]:
year

array([1900., 1901., 1902., 1903., 1904., 1905., 1906., 1907., 1908.,
       1909., 1910., 1911., 1912., 1913., 1914., 1915., 1916., 1917.,
       1918., 1919., 1920.])

In [30]:
populations = data[:, 1:]   # neglecting the year and only taking the populations of hares, lynxes and rabbits
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [31]:
# simple std
populations.std(axis=0) # first axis - column-wise - std

array([20897.90645809, 16254.59153691,  3322.50622558])

In [41]:
# Question: Which species has the highest population each year?
max_population_year_wise_index = populations.argmax(axis=1) # row-wise - maximum value
max_population_year_wise_index

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])

In [44]:
print('Year', 'Category', 'Population')

category = {
            0: 'Hares', 
            1: 'Lynxes',
            2: 'Carrots'
           }

for i in range(20):
    print(int(data[i, 0]), category[max_population_year_wise_index[i]], int(data[i, max_population_year_wise_index[i]]))

Year Category Population
1900 Carrots 4000
1901 Carrots 6100
1902 Hares 1902
1903 Hares 1903
1904 Lynxes 36300
1905 Lynxes 20600
1906 Carrots 19000
1907 Carrots 13000
1908 Carrots 8300
1909 Carrots 9100
1910 Carrots 7400
1911 Carrots 8000
1912 Hares 1912
1913 Hares 1913
1914 Hares 1914
1915 Lynxes 19500
1916 Carrots 29700
1917 Carrots 15800
1918 Carrots 9700
1919 Carrots 10100


# Broadcasting

Basic operations on numpy arrays (addition, etc.) are elementwise

This works on arrays of the same size.
    Nevertheless, It’s also possible to do operations on arrays of different sizes if NumPy can transform these arrays     so that they all have the same size: this conversion is called broadcasting.

The image below gives an example of broadcasting:

![title](broadcasting.png)

**case 2 :**

In [17]:
 

a = np.arange(0, 40, 10)

print(a)

a = np.tile(a, (3, 1))

print(a)

[ 0 10 20 30]
[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]


In [21]:
a = a.T

a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [22]:
b = np.arange(0, 3)

b

array([0, 1, 2])

In [23]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

**case 3 :**

In [25]:
a = np.arange(0, 40, 10)

a

array([ 0, 10, 20, 30])

In [27]:
a = a[:, np.newaxis]

a

array([[ 0],
       [10],
       [20],
       [30]])

In [28]:
b

array([0, 1, 2])

In [29]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [36]:
print(np.newaxis)
print(type(np.newaxis))
print(type(np))
print(type(np.array))

None
<class 'NoneType'>
<class 'module'>
<class 'builtin_function_or_method'>


In [37]:
a.shape

(4, 1)

In [38]:
a

array([[ 0],
       [10],
       [20],
       [30]])

# Array Shape Manipulation

**Flattening - using ravel() method**

In [3]:
a = np.array([[10, 20, 30], [1, 2, 3]])

a

array([[10, 20, 30],
       [ 1,  2,  3]])

In [4]:
print(a.ndim)

2


In [7]:
a.shape()

TypeError: 'tuple' object is not callable

In [6]:
a.shape

(2, 3)

In [9]:
b = a.ravel() # returns a contiguous flattened array. A 1-D array, containing the elements of the input, is returned. A copy is made only if needed.

b

array([10, 20, 30,  1,  2,  3])

In [10]:
np.shares_memory(a, b)

True

In [11]:
id(a), id(b)

(2937728126480, 2937728137712)

In [13]:
id(a[0]), id(b[0])

(2937728507920, 2937728109392)

In [15]:
id(a[0, 0]), id(b[0])

(2937728111184, 2937728111184)

**flattening - transpose of a matrix**

In [17]:
a.T

array([[10,  1],
       [20,  2],
       [30,  3]])

In [18]:
a.T.ravel()

array([10,  1, 20,  2, 30,  3])

**Reshaping**

The inverse operation to flattening

In [23]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a)

[[1 2 3]
 [4 5 6]]


In [24]:
b = a.ravel()

b

array([1, 2, 3, 4, 5, 6])

In [27]:
b = b.reshape((2, 3))

b

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
b[0, 0] = 100

b

array([[100,   2,   3],
       [  4,   5,   6]])

**Note and       Beware: reshape may also return a copy!:**

In [30]:
a = np.zeros((3, 2))

print(a) # 3x2

b = a.T

print(b) # 2x3

b = b.reshape((3, 2))

print(b) # 3x2

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


**Adding a Dimension**

Indexing with the np.newaxis object allows us to add an axis to an array

newaxis is used to increase the dimension of the existing array by one more dimension, when used once. Thus,

1D array will become 2D array

2D array will become 3D array

3D array will become 4D array and so on

In [31]:
z = np.array([1, 2, 3, 4])
z

array([1, 2, 3, 4])

In [33]:
z = z[:, np.newaxis]

print(z)
print(z.ndim)
print(z.shape)

[[1]
 [2]
 [3]
 [4]]
2
(4, 1)


**Dimension Shuffling**

In [35]:
a = np.arange(1, 3*4*3+1).reshape((3, 4, 3))

print(a)
print(a.ndim)
print(a.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]
3
(3, 4, 3)


In [36]:
a[0, 3, 2]

np.int64(12)

**Resizing**

In [38]:
a = np.arange(4)

print(a)
print(a.shape)

a.resize((7,))

print(a)
print(a.shape)

[0 1 2 3]
(4,)
[0 1 2 3 0 0 0]
(7,)


However, it must not be referred to somewhere else:

In [39]:
b = a

b.resize((4,))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [44]:
np.resize(b, (4,))

array([0, 1, 2, 3])

In [45]:
a

array([0, 1, 2, 3, 0, 0, 0])

In [46]:
b

array([0, 1, 2, 3, 0, 0, 0])

# Sorting Data

In [49]:
# sorting the whole data
a = np.array([[5, 2, 3], [7, 1, 4]])

np.sort(a) # by default, sorts along axis=1 (row-wise) - external sorting

array([[2, 3, 5],
       [1, 4, 7]])

In [50]:
a

array([[5, 2, 3],
       [7, 1, 4]])

In [51]:
np.sort(a, axis=0) # sorting along axis=0 (column-wise) - external sorting

array([[5, 1, 3],
       [7, 2, 4]])

In [52]:
a.sort(axis=-1) # sorting along axis=-1 (row-wise) - inplace sorting
a

array([[2, 3, 5],
       [1, 4, 7]])

**Sorting with fancy indexing**

In [53]:
a = np.array([7, 3, 2, 10, 5, 6])

i = np.argsort(a)

i

array([2, 1, 4, 5, 0, 3])

In [54]:
a

array([ 7,  3,  2, 10,  5,  6])

In [55]:
a[i]

array([ 2,  3,  5,  6,  7, 10])